### ISSUE TITLE
hosted version - CORS fails with all browsers

### ISSUE THREAD

**Issue by dtenenba** [afeld/jsonp#158] opened 2019-05-18 04:47 UTC
Hi, again, I have my own fork (https://github.com/FredHutch/jsonp) and my own hosted proxy (https://wiki-json-proxy.fhcrc.org/).

This time I have a CORS failure on all browsers with the following HTML:

```html
<!-- load fetch() polyfill from polyfill.io -->
<script crossorigin="anonymous" src="https://polyfill.io/v3/polyfill.min.js?features=fetch-polyfill"></script>
<script>
    fetch('https://wiki-json-proxy.fhcrc.org/?url=https://jsonview.com/example.json').then(function (data) {
        // alert('pretty awesome, eh? ' + data.awesome);
        console.log(data);
        console.log("done");
    });
</script>
```

If the URL contains `jsonp.afeld.me` instead of my proxy it works fine on all browsers. But when it's my url as above, I get this on firefox:

```
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://wiki-json-proxy.fhcrc.org/?url=https://jsonview.com/example.json. (Reason: CORS request did not succeed).[Learn More]
TypeError: NetworkError when attempting to fetch resource.
```

On Safari and Chrome I get no error, but the data output to the console does not contain any data from the remote server. 

My proxy DOES send the CORS header. Here are the headers it sends:

```
$ curl -I "https://wiki-json-proxy.fhcrc.org/?url=https://jsonview.com/example.json"
HTTP/1.1 200 OK
X-Powered-By: Express
access-control-allow-origin: *
accept-ranges: bytes
cache-control: max-age=0
content-type: application/json; charset=utf-8
date: Sat, 18 May 2019 04:40:46 GMT
expires: Sat, 18 May 2019 04:40:46 GMT
last-modified: Sat, 10 Dec 2016 22:39:12 GMT
upgrade: h2
x-ua-compatible: IE=Edge,chrome=1
Content-Length: 260
ETag: W/"104-SMKkbslSbfSpf7Fvqb31X8kFCk8"
```

Compare this to the headers sent by your proxy:

```
$ curl -I "https://jsonp.afeld.me/?url=https://jsonview.com/example.json"
HTTP/2 200
date: Sat, 18 May 2019 04:39:13 GMT
content-type: application/json; charset=utf-8
set-cookie: __cfduid=daa2d614eb273d7cdd72a0d05b7984d141558154353; expires=Sun, 17-May-20 04:39:13 GMT; path=/; domain=.afeld.me; HttpOnly; Secure
cache-control: max-age=0
accept-ranges: bytes
access-control-allow-origin: *
expect-ct: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
expires: Sat, 18 May 2019 04:39:13 GMT
last-modified: Sat, 10 Dec 2016 22:39:12 GMT
strict-transport-security: max-age=0; preload
x-ua-compatible: IE=Edge,chrome=1
server: cloudflare
cf-ray: 4d8b25658e88c99d-SEA
```

Both are sending `access-control-allow-origin: *` so I am not sure what the problem is.

Any ideas?

Thanks!

**Comment by dtenenba** [comment] 2019-05-18 05:05
Correction - this does NOT work, whether the proxy used is yours (jsonp.afeld.me) or mine (wiki-json-proxy.fhcrc.org). It does not return an error but does not show the data from jsonview.com. The console shows this:

```
Response { type: "cors", url: "https://jsonp.afeld.me/?url=https://jsonview.com/example.json", redirected: false, status: 200, ok: true, statusText: "OK", headers: Headers, body: ReadableStream, bodyUsed: false }
test.html:6:9
done
```

I should note that the server serving my HTML above also sends the CORS header:

```
...
Access-Control-Allow-Origin: *
...
```

Not sure if that matters....

**Comment by dtenenba** [comment] 2019-05-18 05:14
OK, final comment on this (sorry).

Here is some HTML that works when the proxy used is yours and fails when it's mine. 

```html
<!-- load fetch() polyfill from polyfill.io -->
<script crossorigin="anonymous" src="https://polyfill.io/v3/polyfill.min.js?features=fetch-polyfill"></script>
<script>
    fetch('https://wiki-json-proxy.fhcrc.org?url=https://jsonview.com/example.json')
            .then(function (response) {
                return response.json();
            })
            .then(function (myJson) {
                console.log(JSON.stringify(myJson));
            });
</script>
```

Output when proxy is mine:

```
ross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://wiki-json-proxy.fhcrc.org/?url=https://jsonview.com/example.json. (Reason: CORS request did not succeed).[Learn More]
TypeError: NetworkError when attempting to fetch resource.

```


Headers are as above. My proxy is sending the CORS header.  Not sure what's wrong...

**Comment by afeld** [comment] 2019-05-19 04:24
Heh, I'm not able to reproduce this problem either 😛 Are you seeing the `access-control-allow-origin` header in the Network tab of your browser? Is it possible that you have some corporate policy set on your browser or something that might restrict cross-domain requests? Do you have another (personal) machine you can test it on?

Again, closing this issue since it doesn't _seem_ like a JSONProxy problem, but happy to continue helping troubleshoot if I can.

**Closed by afeld** 2019-05-19 04:24 UTC
