### ISSUE TITLE
Allow any http method

### ISSUE THREAD

**Issue by jimmywarting** [afeld/jsonp#175] opened 2020-05-14 12:50 UTC
Respond back with the method they are making:
```js
res.header('Access-Control-Allow-Methods', req.header('Access-Control-Request-Method'))
```
patch, delete, custom, etc

**Comment by afeld** [comment] 2020-05-14 17:23
Duplicate of https://github.com/afeld/jsonp/issues/2.

**Closed by afeld** 2020-05-14 17:23 UTC
